export type Point = { x: number; y: number };
export type BedArea = { id: string; label: string; points: Point[]; closed: boolean; sqft: number; chosenByAi?: boolean };
export type Preferences = { styles: string[]; hardscape: string[]; water: string[]; structures: string[]; mulchType: 'mulch'|'rock'|'none'; mulchDepthIn: 2|3; sunExposure: string; note: string };
export type Plant = { name: string; botanicalName: string; quantity: number; spacingIn: number; matureSize: string; priceEach: number; outsideZone?: boolean };
export type Concept = { id: string; title: string; description: string; imageUrl?: string; areaPlans: { areaId: string; areaLabel: string; plants: Plant[]; placement: string }[]; features: { category: string; name: string; size: string; estimatedCost: number }[]; maintenance: { light: string; water: string; soil: string; feeding: string; pruning: string; winter: string; seasonal: string }; materials: { edgingLengthFt: number } };
const emptyPrefs: Preferences = { styles: [], hardscape: [], water: [], structures: [], mulchType: 'mulch', mulchDepthIn: 2, sunExposure: 'Full sun', note: '' };

type GardenState = { photo?: string; areas: BedArea[]; activeAreaId: string|null; preferences: Preferences; concepts: Concept[]; totalArea: number; setPhoto: (x:string)=>void; addPoint:(p:Point)=>void; undoPoint:()=>void; closeArea:()=>void; addArea:()=>void; deleteArea:(id?:string)=>void; reset:()=>void; updatePreferences:(p:Partial<Preferences>)=>void; setAreas:(a:BedArea[])=>void; setConcepts:(c:Concept[])=>void };
const GardenContext = React.createContext<GardenState | null>(null);
import React, { useMemo, useState } from 'react';
const areaSize = (points: Point[]) => { if (points.length < 3) return 0; let n=0; points.forEach((p,i)=>{const q=points[(i+1)%points.length]; n += p.x*q.y-q.x*p.y}); return Math.max(0, Math.round(Math.abs(n)/2*0.45)); };
export function GardenProvider({children}:{children:React.ReactNode}) { const [photo,setPhoto]=useState<string>(); const [areas,setAreas]=useState<BedArea[]>([{id:'area-1',label:'Area 1',points:[],closed:false,sqft:0}]); const [activeAreaId,setActive]=useState<string|null>('area-1'); const [preferences,setPrefs]=useState(emptyPrefs); const [concepts,setConcepts]=useState<Concept[]>([]);
 const active=areas.find(a=>a.id===activeAreaId); const update=(fn:(a:BedArea)=>BedArea)=>setAreas(as=>as.map(a=>a.id===activeAreaId?fn(a):a));
 const value=useMemo<GardenState>(()=>({photo,areas,activeAreaId,preferences,concepts,totalArea:areas.reduce((n,a)=>n+a.sqft,0),setPhoto, setAreas, setConcepts, addPoint:p=>active&&!active.closed&&update(a=>({...a,points:[...a.points,p]})), undoPoint:()=>update(a=>({...a,points:a.points.slice(0,-1)})), closeArea:()=>update(a=>a.points.length>=3?({...a,closed:true,sqft:areaSize(a.points)}):a), addArea:()=>{const id=`area-${Date.now()}`;setAreas(as=>[...as,{id,label:`Area ${as.length+1}`,points:[],closed:false,sqft:0}]);setActive(id)}, deleteArea:(id=activeAreaId||undefined)=>{setAreas(as=>{const next=as.filter(a=>a.id!==id); return next.length?next:[{id:'area-1',label:'Area 1',points:[],closed:false,sqft:0}]});setActive(null)}, reset:()=>{setPhoto(undefined);setAreas([{id:'area-1',label:'Area 1',points:[],closed:false,sqft:0}]);setActive('area-1');setConcepts([])},updatePreferences:p=>setPrefs(x=>({...x,...p}))}),[photo,areas,activeAreaId,preferences,concepts]); return <GardenContext.Provider value={value}>{children}</GardenContext.Provider> }
export function useGarden(){const v=React.useContext(GardenContext);if(!v)throw Error('GardenProvider missing');return v}
